#!/bin/sh

#
# Copyright 2019 Arcus Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Look at argument to determine how to handle file
echo "Installing firmware file $1"

# If *update.bin file, use fwinstall
# use update for other cases...
if echo $1 | grep -q "_update" ; then
    fwinstall -k $1
elif echo $1 | grep -q "http:" ; then
    update -kf $1
elif echo $1 | grep -q "file:" ; then
    update -kf $1
else
    update -kf file://$1
fi

