#!/bin/sh

# Get config file
[ -f /etc/ifplugd/ifplugd.conf ] && . /etc/ifplugd/ifplugd.conf

[ "x$INTERFACES" = "xauto" ] && INTERFACES="`cat /proc/net/dev | awk '{ print $1 }' | egrep '^(eth|ppp)' | cut -d
: -f1`"

# Handle argument
case "$1" in
  start)
        echo -n "Starting ifplugd: "
        for IF in $INTERFACES ; do
            A="`eval echo \$\{ARGS_${IF}\}`"
            [ -z "$A" ] && A="$ARGS"
            /usr/sbin/ifplugd -i $IF $A
            echo -n " $IF"
        done
        echo
        ;;
  stop)
        echo -n "Shutting down ifplugd: "
        killall ifplugd
        ;;
  restart)
        $0 stop $INTERFACES
        $0 start $INTERFACES
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
