#!/bin/sh

#
# Copyright 2019 Arcus Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

echo Setting up 4G dongle support...

# Create lteControl file
touch /tmp/lteControl
chmod 0666 /tmp/lteControl

# Create backupStatus file
touch /tmp/backupStatus
chmod 0666 /tmp/backupStatus

# Create lte_interface file
touch /tmp/lte_interface
chmod 0666 /tmp/lte_interface

# Launch IRIS Hub 4G daemon
iris4gd

